const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { spawnSync } = require("node:child_process");
const { test } = require("node:test");
const { inspectSkillPayload } = require("../src/lib/skillPayload");

const packageRoot = path.resolve(__dirname, "..");
const cli = path.join(packageRoot, "bin", "lithermes.js");
const pluginRoot = path.join(packageRoot, "assets", "lithermes-plugin");
const representativeNestedSkills = [
  ["autoresearch", "modes/core/SKILL.md"],
  ["autoconference", "modes/core/SKILL.md"],
];

function run(args) {
  return spawnSync(process.execPath, [cli, ...args], {
    cwd: packageRoot,
    encoding: "utf8",
    env: { ...process.env, CI: "1", NO_UPDATE_NOTIFIER: "1" },
    timeout: 30000,
  });
}

test("doctor verifies every registered nested skill asset hash", (t) => {
  const home = fs.mkdtempSync(path.join(os.tmpdir(), "lithermes-nested-integrity."));
  t.after(() => fs.rmSync(home, { recursive: true, force: true }));
  const install = run(["install", "--yes", "--offline", "--no-hud", "--hermes-home", home]);
  assert.equal(install.status, 0, install.stdout + install.stderr);

  const nested = path.join(
    home,
    "plugins",
    "lithermes",
    "skills",
    "frontend-ui-ux",
    "resources",
    "design-intelligence.json",
  );
  fs.appendFileSync(nested, "\n");
  const doctor = run(["doctor", "--offline", "--hermes-home", home]);
  assert.equal(doctor.status, 1, doctor.stdout + doctor.stderr);
  assert.match(doctor.stdout, /installed skill payload: FAIL/i);
  assert.match(doctor.stdout, /frontend-ui-ux.*design-intelligence\.json.*hash mismatch/i);
});

test("source payload inspection hash-checks representative nested family SKILL.md files", (t) => {
  const temp = fs.mkdtempSync(path.join(os.tmpdir(), "lithermes-nested-source-integrity."));
  t.after(() => fs.rmSync(temp, { recursive: true, force: true }));
  const copiedPlugin = path.join(temp, "lithermes");
  fs.cpSync(pluginRoot, copiedPlugin, { recursive: true });
  const manifest = JSON.parse(fs.readFileSync(path.join(copiedPlugin, "payload-version.json"), "utf8"));
  for (const [family, relative] of representativeNestedSkills) {
    fs.appendFileSync(path.join(copiedPlugin, "skills", family, ...relative.split("/")), "\n");
  }

  const inspection = inspectSkillPayload(copiedPlugin, manifest, true);
  assert.equal(inspection.ok, false);
  for (const [family, relative] of representativeNestedSkills) {
    assert.ok(
      inspection.failures.some(
        (failure) => failure.id === family && failure.path === relative && failure.reason === "hash mismatch",
      ),
      `${family}/${relative} was not hash-checked: ${JSON.stringify(inspection)}`,
    );
  }
});

test("installed doctor hash-checks representative nested family SKILL.md files", (t) => {
  const home = fs.mkdtempSync(path.join(os.tmpdir(), "lithermes-nested-family-integrity."));
  t.after(() => fs.rmSync(home, { recursive: true, force: true }));
  const install = run(["install", "--yes", "--offline", "--no-hud", "--hermes-home", home]);
  assert.equal(install.status, 0, install.stdout + install.stderr);
  const installedPlugin = path.join(home, "plugins", "lithermes");
  for (const [family, relative] of representativeNestedSkills) {
    fs.appendFileSync(path.join(installedPlugin, "skills", family, ...relative.split("/")), "\n");
  }

  const doctor = run(["doctor", "--offline", "--hermes-home", home]);
  assert.equal(doctor.status, 1, doctor.stdout + doctor.stderr);
  assert.match(doctor.stdout, /installed skill payload: FAIL/i);
  for (const [family, relative] of representativeNestedSkills) {
    const escaped = `${family}/${relative}`.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    assert.match(doctor.stdout, new RegExp(`${escaped} hash mismatch`, "i"));
  }
});

test("doctor rejects unmanifested Python bytecode instead of ignoring it", (t) => {
  const home = fs.mkdtempSync(path.join(os.tmpdir(), "lithermes-unmanifested-bytecode."));
  t.after(() => fs.rmSync(home, { recursive: true, force: true }));
  const install = run(["install", "--yes", "--offline", "--no-hud", "--hermes-home", home]);
  assert.equal(install.status, 0, install.stdout + install.stderr);

  const cache = path.join(home, "plugins", "lithermes", "skills", "wikify", "__pycache__");
  fs.mkdirSync(cache, { recursive: true });
  fs.writeFileSync(path.join(cache, "unmanifested.cpython-312.pyc"), "not generated by the manifest\n");

  const doctor = run(["doctor", "--offline", "--hermes-home", home]);

  assert.equal(doctor.status, 1, doctor.stdout + doctor.stderr);
  assert.match(doctor.stdout, /installed skill payload: FAIL/i);
  assert.match(doctor.stdout, /__pycache__.*unexpected|unmanifested.*unexpected/i);
});

test("payload inspection fails closed when directory traversal throws", () => {
  const manifest = JSON.parse(
    fs.readFileSync(path.join(pluginRoot, "payload-version.json"), "utf8"),
  );
  const inspection = inspectSkillPayload(pluginRoot, manifest, true, {
    readDirectory(directory, options) {
      if (directory.endsWith(path.join("skills", "visual-qa"))) {
        throw new Error("injected traversal failure");
      }
      return fs.readdirSync(directory, options);
    },
  });

  assert.equal(inspection.ok, false, "a traversal error must never collapse to an empty PASS inventory");
  assert.ok(
    inspection.failures.some(
      (failure) => failure.id === "payload" && failure.reason === "traversal failed",
    ),
    JSON.stringify(inspection),
  );
});

test("doctor rejects an unreadable unlisted directory when permissions are enforced", (t) => {
  const home = fs.mkdtempSync(path.join(os.tmpdir(), "lithermes-unreadable-integrity."));
  t.after(() => fs.rmSync(home, { recursive: true, force: true }));
  const install = run(["install", "--yes", "--offline", "--no-hud", "--hermes-home", home]);
  assert.equal(install.status, 0, install.stdout + install.stderr);
  const locked = path.join(
    home,
    "plugins",
    "lithermes",
    "skills",
    "visual-qa",
    "scripts",
    "unreadable-unlisted",
  );
  fs.mkdirSync(locked);
  fs.writeFileSync(path.join(locked, "hidden.py"), "pass\n");
  fs.chmodSync(locked, 0o000);
  let permissionEnforced = false;
  try {
    fs.readdirSync(locked);
  } catch {
    permissionEnforced = true;
  }

  const doctor = run(["doctor", "--offline", "--hermes-home", home]);
  fs.chmodSync(locked, 0o700);
  assert.equal(doctor.status, 1, doctor.stdout + doctor.stderr);
  assert.match(doctor.stdout, /installed skill payload: FAIL/i);
  assert.match(
    doctor.stdout,
    permissionEnforced ? /traversal failed/i : /unreadable-unlisted.*unexpected/i,
  );
});

for (const [label, mutate, expected] of [
  [
    "shared UIUX runtime tamper",
    (plugin) => fs.appendFileSync(path.join(plugin, "uiux_runtime_common.py"), "\n"),
    /uiux_runtime_common\.py.*hash mismatch/i,
  ],
  [
    "shared UIUX runtime missing",
    (plugin) => fs.rmSync(path.join(plugin, "uiux_runtime_common.py")),
    /uiux_runtime_common\.py.*missing/i,
  ],
  [
    "unexpected unlisted plugin entry",
    (plugin) => fs.writeFileSync(path.join(plugin, "skills", "visual-qa", "scripts", "unlisted.py"), "pass\n"),
    /unlisted\.py.*unexpected/i,
  ],
  [
    "unexpected empty plugin directory",
    (plugin) => fs.mkdirSync(path.join(plugin, "skills", "visual-qa", "unlisted-directory")),
    /unlisted-directory.*unexpected/i,
  ],
]) {
  test(`doctor rejects ${label}`, (t) => {
    const home = fs.mkdtempSync(path.join(os.tmpdir(), "lithermes-payload-integrity."));
    t.after(() => fs.rmSync(home, { recursive: true, force: true }));
    const install = run(["install", "--yes", "--offline", "--no-hud", "--hermes-home", home]);
    assert.equal(install.status, 0, install.stdout + install.stderr);
    mutate(path.join(home, "plugins", "lithermes"));

    const doctor = run(["doctor", "--offline", "--hermes-home", home]);
    assert.equal(doctor.status, 1, doctor.stdout + doctor.stderr);
    assert.match(doctor.stdout, /installed skill payload: FAIL/i);
    assert.match(doctor.stdout, expected);
  });
}
