"""Accessibility, routing, spacing, boundary, and canvas checks for SVG."""

from __future__ import annotations

import math
import re
import colorsys

from diagram_geometry import parse_svg
from diagram_metrics import DiagramMetrics, source_metrics
from diagram_quality_geometry import (
    distance_to_rect_boundary, marker_length, marker_overlaps_rect, marker_scale,
    marker_tip, rectangle_gap, route_bends, route_crosses_boundary,
    route_crossings, route_distance, route_length, route_manhattan_distance,
    routes_overlap_collinearly, segment_along_boundary, segment_hits_rect,
    segment_hits_text, text_overlaps_node,
)
from diagram_records import Boundary, ParsedSvg, Route, Shape, TextBox
from diagram_sequence import sequence_issues

_CONTAMINATION = (
    re.compile(r"\blitfamily\b", re.IGNORECASE),
    re.compile(r"\b(?:generator|generated by|template|prototype)\b", re.IGNORECASE),
    re.compile(r"\bsource\s*:", re.IGNORECASE),
    re.compile(r"\bnotes?\s*:", re.IGNORECASE),
    re.compile(r"\bstatic\s+first\b", re.IGNORECASE),
    re.compile(r"\baccessible\s+labels\b", re.IGNORECASE),
    re.compile(r"\bone\s+accent\b", re.IGNORECASE),
    re.compile(r"\bfocal\b", re.IGNORECASE),
    re.compile(r"\b(?:light|dark|full)\s*[·|/]\s*static\b", re.IGNORECASE),
    re.compile(r"\bdesign\s+rules?\b", re.IGNORECASE),
    re.compile(r"^\s*show\b", re.IGNORECASE),
)

OFFICE_RULES = {
    "group_ratio": 2, "accent_saturation": .12, "accent_light_min": .12,
    "accent_light_max": .93, "accent_hue_family_deg": 20,
    "accent_medium_count": 3, "accent_high_count": 4,
    "latin_share": .80, "title_case_share": .60,
    "label_inset_px": 4,
}


def _office_craft_issues(parsed: ParsedSvg, nodes: tuple[Shape, ...]) -> list[str]:
    issues: list[str] = []
    if len(parsed.boundaries) >= 2:
        def group(shape: Shape) -> str:
            center = (shape.rect.x + shape.rect.w / 2, shape.rect.y + shape.rect.h / 2)
            for boundary in parsed.boundaries:
                if boundary.rect.x <= center[0] <= boundary.rect.right and boundary.rect.y <= center[1] <= boundary.rect.bottom:
                    return boundary.name
            return "unbounded"

        within, between = [], []
        for index, first in enumerate(nodes):
            for second in nodes[index + 1:]:
                gap = rectangle_gap(first.rect, second.rect)
                (within if group(first) == group(second) else between).append(gap)
        if within and between and min(between) < OFFICE_RULES["group_ratio"] * max(within):
            issues.append(f"OF-201 group ratio {min(between) / max(within):.2f} below {OFFICE_RULES['group_ratio']}")

    hues: list[float] = []
    for node in nodes:
        if node.attributes.get("display") == "none" or not re.fullmatch(r"#[0-9a-fA-F]{6}", node.fill):
            continue
        rgb = tuple(int(node.fill[index:index + 2], 16) / 255 for index in (1, 3, 5))
        hue, lightness, saturation = colorsys.rgb_to_hls(*rgb)
        hue *= 360
        if saturation < OFFICE_RULES["accent_saturation"] or not OFFICE_RULES["accent_light_min"] <= lightness <= OFFICE_RULES["accent_light_max"]:
            continue
        if not any(min(abs(hue - prior), 360 - abs(hue - prior)) <= OFFICE_RULES["accent_hue_family_deg"] for prior in hues):
            hues.append(hue)
    if len(hues) >= OFFICE_RULES["accent_medium_count"]:
        level = "HIGH" if len(hues) >= OFFICE_RULES["accent_high_count"] else "MEDIUM"
        issues.append(f"OF-202 {level} accent families={len(hues)}")

    for text in parsed.texts:
        label = text.label.strip()
        latin = sum(character.isascii() and character.isalnum() for character in label)
        if label and latin / len(label) >= OFFICE_RULES["latin_share"] and label != label.upper():
            words = re.findall(r"[A-Za-z]{4,}", label)
            capitals = sum(bool(re.fullmatch(r"[A-Z][a-z]+", word)) for word in words)
            function_word = re.search(r"\b(?:Of|And|The|To|For|In)\b", label)
            if len(words) >= 2 and capitals / len(words) > OFFICE_RULES["title_case_share"] and function_word:
                issues.append(f"OF-203 MEDIUM title-case label={label}")
        if text.edge_for:
            continue  # Edge labels have no stable inner box in this parser.
        box = next((boundary.rect for boundary in parsed.boundaries if boundary.name == text.boundary_for), None) if text.boundary_for else None
        if box is None and text.role == "node":
            box = next((node.rect for node in nodes if node.rect.x <= text.anchor[0] <= node.rect.right and
                        node.rect.y <= text.anchor[1] <= node.rect.bottom), None)
        if box is not None and text.bounds.w > box.w - OFFICE_RULES["label_inset_px"]:
            issues.append(f"OF-204 label {label} width={text.bounds.w:.1f}px exceeds {box.w - OFFICE_RULES['label_inset_px']:.1f}px")
    return issues


def _node_shapes(parsed: ParsedSvg) -> tuple[Shape, ...]:
    return tuple(shape for shape in parsed.shapes if shape.attributes.get("data-node-id"))


def _node_by_id(nodes: tuple[Shape, ...], name: str) -> Shape | None:
    return next((node for node in nodes if node.attributes.get("data-node-id") == name), None)


def _boundary_label(text: TextBox, outlines: tuple[Boundary, ...]) -> bool:
    return text.role == "boundary" or bool(text.boundary_for) or any(text.label in boundary.labels or text.boundary_for == boundary.name for boundary in outlines)


def _boundary_edges(boundary: Boundary) -> tuple[tuple[float, float, float, float], ...]:
    rect = boundary.rect
    return ((rect.x, rect.y, rect.right, rect.y), (rect.right, rect.y, rect.right, rect.bottom), (rect.right, rect.bottom, rect.x, rect.bottom), (rect.x, rect.bottom, rect.x, rect.y))


def _marker_id(value: str) -> str:
    match = re.search(r"url\(\s*['\"]?#([^\s)'\"`]+)['\"]?\s*\)", value, re.IGNORECASE)
    return match.group(1) if match else ""


def _aligned_route(route: Route, nodes: tuple[Shape, ...]) -> str:
    origin, target = _node_by_id(nodes, route.from_id), _node_by_id(nodes, route.to_id)
    if origin is None or target is None or not route.segments:
        return ""
    same_row = abs(origin.rect.y + origin.rect.h / 2 - target.rect.y - target.rect.h / 2) <= 1
    same_column = abs(origin.rect.x + origin.rect.w / 2 - target.rect.x - target.rect.w / 2) <= 1
    horizontal = all(abs(y1 - y2) <= 1 for _, y1, _, y2 in route.segments)
    vertical = all(abs(x1 - x2) <= 1 for x1, _, x2, _ in route.segments)
    origin_x, target_x = origin.rect.x + origin.rect.w / 2, target.rect.x + target.rect.w / 2
    origin_y, target_y = origin.rect.y + origin.rect.h / 2, target.rect.y + target.rect.h / 2
    row_clear = all(
        node is origin or node is target
        or abs(node.rect.y + node.rect.h / 2 - origin_y) > 1
        or node.rect.x + node.rect.w / 2 <= min(origin_x, target_x)
        or node.rect.x + node.rect.w / 2 >= max(origin_x, target_x)
        for node in nodes
    )
    column_clear = all(
        node is origin or node is target
        or abs(node.rect.x + node.rect.w / 2 - origin_x) > 1
        or node.rect.y + node.rect.h / 2 <= min(origin_y, target_y)
        or node.rect.y + node.rect.h / 2 >= max(origin_y, target_y)
        for node in nodes
    )
    if same_row and row_clear and not horizontal:
        return "same-row"
    if same_column and column_clear and not vertical:
        return "same-column"
    return ""


def _decision_issues(nodes: tuple[Shape, ...], routes: tuple[Route, ...]) -> list[str]:
    issues: list[str] = []
    for node in nodes:
        if node.attributes.get("data-node-type") != "decision":
            continue
        name = node.attributes["data-node-id"]
        outcomes = [value.strip() for value in node.attributes.get("data-outcomes", "").split("|") if value.strip()]
        if len(outcomes) < 2:
            issues.append(f"DECISION_OUTCOMES_MISSING {name} must name at least two outcomes")
            continue
        labels = {route.label for route in routes if route.from_id == name and route.label}
        issues.extend(f"DECISION_OUTCOME_MISSING {name} {outcome}" for outcome in outcomes if outcome not in labels)
        issues.extend(f"DECISION_OUTCOME_UNDECLARED {name} {label}" for label in labels if label not in outcomes)
    return issues


def _route_issues(parsed: ParsedSvg, metrics: DiagramMetrics, nodes: tuple[Shape, ...]) -> list[str]:
    issues: list[str] = []
    sequence = bool(re.search(r"\bdata-type\s*=\s*['\"]sequence(?:-oauth)?['\"]", parsed.source, re.IGNORECASE))
    for text in parsed.texts:
        if text.role != "edge" and not text.edge_for:
            continue
        matches = [route for route in parsed.routes if f"{route.from_id}|{route.to_id}" == text.edge_for and (not route.label or route.label == text.label)]
        if not text.edge_for or len(matches) != 1:
            issues.append(f"EDGE_LABEL_UNBOUND {text.edge_for or text.label}")
            continue
        route = matches[0]
        own = route_distance(text.anchor, route)
        other = min((route_distance(text.anchor, item) for item in parsed.routes if item is not route), default=math.inf)
        if own > 24:
            issues.append(f"EDGE_LABEL_TOO_FAR {text.label} own={own:.1f}px max=24px")
        if math.isfinite(other) and own >= other:
            issues.append(f"EDGE_LABEL_NEAREST_PATH {text.label} own={own:.1f}px other={other:.1f}px")
        for node in nodes:
            if text_overlaps_node(text, node.rect):
                issues.append(f"EDGE_LABEL_NODE_COLLISION {text.label} overlaps {node.attributes['data-node-id']}")
    for route in parsed.routes:
        distance = route_manhattan_distance(route)
        ratio = route_length(route) / distance if distance else 1
        if ratio > 1.4:
            issues.append(f"ROUTE_DETOUR {route.from_id}->{route.to_id} ratio={ratio:.2f} max=1.40")
        aligned = _aligned_route(route, nodes)
        if aligned:
            issues.append(f"ROUTE_ALIGNED_PATH {route.from_id}->{route.to_id} {aligned} neighbors require one straight segment")
        crosses = any(route_crosses_boundary(route, boundary) for boundary in parsed.boundaries)
        limit = 3 if crosses else 2
        bends = route_bends(route)
        if bends > limit:
            issues.append(f"ROUTE_BENDS {route.from_id}->{route.to_id} bends={bends} max={limit}")
        if route.marker_start and route.marker_end:
            issues.append(f"ROUTE_OPPOSED_HEADS {route.from_id}->{route.to_id}")
        for text in parsed.texts:
            if any(segment_hits_text(segment, text) for segment in route.segments):
                issues.append(f"EDGE_TEXT_COLLISION {route.from_id}->{route.to_id}: {text.label}")
                break
        for node in nodes:
            if node.attributes.get("data-node-id") not in {route.from_id, route.to_id} and any(segment_hits_rect(segment, node.rect, 8) for segment in route.segments):
                issues.append(f"ROUTE_THROUGH_NODE {route.from_id}->{route.to_id} via {node.attributes['data-node-id']}")
        if any(segment_along_boundary(segment, boundary) for boundary in parsed.boundaries for segment in route.segments):
            issues.append(f"ROUTE_ALONG_BOUNDARY {route.from_id}->{route.to_id}")
        target = _node_by_id(nodes, route.to_id)
        if route.marker_end:
            marker = parsed.markers.get(_marker_id(route.marker_end))
            minimum = max(5 * route.stroke_width, (metrics["viewBox"].w if metrics["viewBox"] else 1080) * 12 / 1080)
            if marker is None:
                issues.append(f"ARROWHEAD_GEOMETRY_MISSING {route.from_id}->{route.to_id} end")
            elif marker_length(marker) * marker_scale(marker, route) + 0.01 < minimum:
                issues.append(f"ARROWHEAD_SIZE_FLOOR {route.from_id}->{route.to_id} end min={minimum:.1f}px")
            if marker is not None and target is not None and not sequence:
                tip = marker_tip(route, marker, "end")
                if tip is not None and distance_to_rect_boundary(tip, target.rect) > 2:
                    issues.append(f"ARROWHEAD_TIP_MISSED_TARGET {route.from_id}->{route.to_id}")
            if marker is not None and target is not None and marker_overlaps_rect(route, target.rect, marker):
                issues.append(f"ARROWHEAD_TARGET_OVERLAP {route.from_id}->{route.to_id} marker intersects target {route.to_id}")
    for index, first in enumerate(parsed.routes):
        for second in parsed.routes[index + 1:]:
            if routes_overlap_collinearly(first, second):
                issues.append(f"ROUTE_COLLINEAR_OVERLAP {first.from_id}->{first.to_id} / {second.from_id}->{second.to_id} shared within 12px")
            for x, y in route_crossings(first, second):
                issues.append(f"ROUTE_CROSSING {first.from_id}->{first.to_id} / {second.from_id}->{second.to_id} at {x:.1f},{y:.1f}")
    return issues


def quality_issues(source: str, *, enforce_canvas: bool = False, scale: float | None = None) -> list[str]:
    """Return stable issue codes for geometry, readability, and accessibility defects."""
    parsed = parse_svg(source)
    metrics = source_metrics(source)
    nodes = _node_shapes(parsed)
    issues: list[str] = []
    contaminated = list(dict.fromkeys(text.label for text in parsed.texts if any(rule.search(text.label) for rule in _CONTAMINATION)))
    if contaminated:
        issues.append("PROCESS_TEXT " + " | ".join(contaminated))
    if not metrics["hasSvg"]:
        issues.append("SVG_MISSING")
        return issues
    for key, code in (("title", "SVG_TITLE_MISSING"), ("desc", "SVG_DESC_MISSING"), ("roleImage", "SVG_ROLE_IMAGE_MISSING"), ("ariaLinked", "SVG_ARIA_LINK_MISSING")):
        if not metrics[key]:
            issues.append(code)
    if metrics["offCanvas"]:
        issues.append("OFF_CANVAS " + " | ".join(metrics["offCanvasLabels"]))
    if metrics["textOverlaps"]:
        issues.append(f"TEXT_OVERLAP count={metrics['textOverlaps']}")
    if metrics["objectOverlaps"]:
        issues.append(f"OBJECT_OVERLAP count={metrics['objectOverlaps']}")
    for failure in metrics["contrastFailures"]:
        issues.append(f"CONTRAST_FLOOR {failure['text']}={failure['ratio']}:1")
    issues.extend(_route_issues(parsed, metrics, nodes))
    issues.extend(_decision_issues(nodes, parsed.routes))
    issues.extend(sequence_issues(source, parsed, nodes))
    for text in parsed.texts:
        for boundary in parsed.boundaries:
            if any(segment_hits_text(edge, text, boundary.stroke_width / 2 + 0.5) for edge in _boundary_edges(boundary)):
                issues.append(f"OUTLINE_TEXT_COLLISION {text.label} crosses {boundary.name}")
                break
    boundary_failures = {failure["text"] for failure in metrics["contrastFailures"]}
    for text in parsed.texts:
        if _boundary_label(text, parsed.boundaries) and text.label in boundary_failures:
            issues.append(f"BOUNDARY_CONTRAST_FLOOR {text.label} below 4.5:1")
    for index, first in enumerate(nodes):
        for second in nodes[index + 1:]:
            if rectangle_gap(first.rect, second.rect) < 12:
                issues.append(f"NODE_GAP {first.attributes['data-node-id']}/{second.attributes['data-node-id']} below 12px")
    issues.extend(_office_craft_issues(parsed, nodes))
    if enforce_canvas:
        ratio = scale if scale is not None else min(metrics["viewBox"].w / 1080, metrics["viewBox"].h / 640) if metrics["viewBox"] else 1
        if not any(text.role == "title" for text in parsed.texts):
            issues.append('TITLE_ROLE_MISSING visible title must use data-role="title"')
        for text in parsed.texts:
            boundary_text = _boundary_label(text, parsed.boundaries)
            minimum = 28 if text.role == "title" else 13 if text.role == "edge" or boundary_text else 15 if text.role == "node" else 0
            if minimum and text.font_size + 0.01 < minimum * ratio:
                detail = f"{text.role or 'boundary'}:{text.label}={text.font_size}px (min {minimum * ratio:.1f}px)"
                issues.append(f"BOUNDARY_FONT_FLOOR {detail}" if boundary_text else "FONT_FLOOR " + detail)
        points = [(node.rect.x, node.rect.y) for node in nodes] + [(node.rect.right, node.rect.bottom) for node in nodes]
        points.extend(point for route in parsed.routes for segment in route.segments for point in ((segment[0], segment[1]), (segment[2], segment[3])))
        if nodes and metrics["viewBox"] and points:
            left, top = min(point[0] for point in points), min(point[1] for point in points)
            right, bottom = max(point[0] for point in points), max(point[1] for point in points)
            width, height = (right - left) / (metrics["viewBox"].w * 0.90), (bottom - top) / (metrics["viewBox"].h * 0.74)
            if width < 0.75 or height < 0.54:
                issues.append(f"CONTENT_FILL safe-area-width={width:.3f} safe-area-height={height:.3f} minimum=.75/.54")
        if not nodes:
            issues.append("CONTENT_NODES_MISSING")
    return list(dict.fromkeys(issues))
